import { useEffect } from "react";
import { Link, useParams } from "wouter";
import { ArrowLeft, ArrowRight, Calendar, MapPin, Sparkles } from "lucide-react";
import { AdSlot } from "@/components/ads/AdSlot";

type Post = { slug: string; title: string; description: string; date: string; read: string; image: string; sections: { heading: string; paragraphs: string[] }[] };
export const POSTS: Post[] = [
  { slug: "best-things-to-do-puerto-rico-local-guide", title: "Best Things to Do in Puerto Rico: A Local-First Guide", description: "Discover beaches, waterfalls, food, surf towns, and locally guided experiences across Puerto Rico while supporting island businesses.", date: "July 12, 2026", read: "8 min read", image: "/images/hero-crash-boat.png", sections: [
    { heading: "Start with the Puerto Rico you cannot find in a resort brochure", paragraphs: ["Puerto Rico rewards curious travelers. Old San Juan and El Yunque deserve their fame, but the island’s character also lives in neighborhood bakeries, family restaurants, west-coast sunsets, mountain swimming holes, and small tour companies led by people who grew up nearby.", "A strong Puerto Rico itinerary mixes one or two iconic destinations with local businesses and quieter places. Spotlight Puerto Rico organizes those options by town, making it easier to build a realistic day instead of spending hours driving from one end of the island to the other."] },
    { heading: "Choose a region and explore deeply", paragraphs: ["For surf, sunsets, and relaxed beach towns, explore Rincón, Aguadilla, and Isabela. The north offers caves, dramatic coastline, and communities such as Arecibo and Manatí. The east is ideal for El Yunque, Fajardo, and island excursions. The central mountains offer coffee country, scenic roads, and cooler air.", "Keep most stops in the same municipality or neighboring towns. You will experience more and spend less of your vacation in traffic. Spotlight’s Trip Builder includes distance and stop controls specifically for this purpose."] },
    { heading: "Book with local guides and save the places that matter", paragraphs: ["Local guides add context, safety, and access—especially for rainforest hikes, caves, snorkeling, surf sessions, and bio bay visits. Use onsite booking and messaging so questions, dates, and confirmations stay together.", "Save businesses, places, and experiences as you browse. A short list built before your trip makes spontaneous days easier without turning the vacation into a rigid schedule."] },
  ]},
  { slug: "el-yunque-tour-airport-hotel-pickup", title: "El Yunque Tours with Airport or Hotel Pickup", description: "Plan an El Yunque rainforest tour with convenient San Juan airport or hotel pickup, local guidance, waterfalls, and swimming stops.", date: "July 12, 2026", read: "6 min read", image: "/images/weeepaaa/el-yunque-tour.jpg", sections: [
    { heading: "A simpler way to experience El Yunque", paragraphs: ["El Yunque National Forest is one of Puerto Rico’s essential natural experiences, but transportation and changing access conditions can complicate a first visit. A guided tour with pickup removes the hardest part of the plan and lets travelers focus on the rainforest.", "Weeepaaa Tours, led by Carlos, offers El Yunque adventures with pickup available from Luis Muñoz Marín International Airport or your hotel. Final pickup details and availability can be confirmed through Spotlight’s onsite booking flow."] },
    { heading: "What to expect on a rainforest day", paragraphs: ["Expect humid tropical weather, uneven ground, waterfalls, and potential swimming opportunities. Wear shoes with traction, bring water, and pack a dry change of clothes. Rain is part of the ecosystem, so a light rain layer is more useful than an umbrella.", "A local guide can adjust the experience to weather, trail conditions, and the group. That flexibility is valuable in a living rainforest where conditions can change quickly."] },
    { heading: "Booking and pickup tips", paragraphs: ["Share your party size, preferred date, pickup location, and any mobility concerns when requesting the tour. If you are arriving by air, leave enough time for baggage collection and possible flight delays.", "Keep communication onsite until the booking is confirmed. This preserves the request history and makes it easier for both traveler and guide to track details."] },
  ]},
  { slug: "support-local-businesses-puerto-rico", title: "How to Find and Support Local Businesses in Puerto Rico", description: "Find trusted Puerto Rico restaurants, shops, services, and experiences while keeping more travel spending in local communities.", date: "July 12, 2026", read: "7 min read", image: "/images/hero-business-bg.png", sections: [
    { heading: "Why local discovery matters", paragraphs: ["Choosing locally owned restaurants, shops, guides, and service providers keeps more visitor spending in Puerto Rican communities. It also produces a more memorable trip: recommendations become conversations, meals reflect the town, and purchases have a story.", "The challenge is discovery. Small businesses may have limited websites, inconsistent hours across platforms, or social profiles that are difficult for visitors to find. A Puerto Rico-focused directory reduces that friction."] },
    { heading: "Use location, recent details, and community reviews", paragraphs: ["Search by municipality first, then compare categories, photos, and recent reviews. Save promising options rather than opening dozens of browser tabs. When possible, confirm hours before a long drive—especially around holidays or weather events.", "Reviews are most useful when they describe specific experiences: what was ordered, how the service worked, accessibility, parking, or who the business is best for. Spotlight swipes are private and never change business ratings; only submitted reviews contribute to reputation."] },
    { heading: "Build local businesses into every day", paragraphs: ["Pair a beach or waterfall with a nearby lunch, coffee stop, shop, or guided experience. This creates a realistic route and spreads economic impact beyond the most visited attractions.", "Spotlight Puerto Rico lets you save these combinations, create trip plans, and return to them from your account. The result is less searching during the trip and more time experiencing the island."] },
  ]},
];

export default function Blog() {
  useEffect(() => { document.title = "Puerto Rico Travel Tips & Local Guides | Spotlight Puerto Rico"; return () => { document.title = "Spotlight Puerto Rico"; }; }, []);
  return <div className="min-h-screen bg-slate-50"><div className="bg-gradient-to-br from-teal-900 to-slate-950 text-white"><div className="container mx-auto px-4 py-14 max-w-5xl"><p className="text-emerald-300 text-sm font-bold flex items-center gap-2"><Sparkles className="w-4 h-4" /> Local knowledge</p><h1 className="font-display text-4xl md:text-5xl font-bold text-white mt-2">Puerto Rico travel guides</h1><p className="text-white/70 max-w-2xl mt-3">Practical island advice, realistic itineraries, and local-first recommendations.</p></div></div><div className="container mx-auto px-4 py-9 max-w-5xl grid md:grid-cols-3 gap-5">{POSTS.map((post) => <Link key={post.slug} href={`/blog/${post.slug}`}><article className="h-full bg-white rounded-2xl overflow-hidden border shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all"><img src={post.image} alt="" className="w-full h-44 object-cover" /><div className="p-5"><p className="text-xs text-muted-foreground flex items-center gap-1"><Calendar className="w-3.5 h-3.5" />{post.date} · {post.read}</p><h2 className="font-display text-xl font-bold mt-2">{post.title}</h2><p className="text-sm text-muted-foreground mt-2 line-clamp-3">{post.description}</p><span className="inline-flex items-center gap-1 text-primary text-sm font-bold mt-4">Read guide <ArrowRight className="w-4 h-4" /></span></div></article></Link>)}</div></div>;
}

export function BlogPost() {
  const { slug } = useParams(); const post = POSTS.find((item) => item.slug === slug);
  useEffect(() => { if (!post) return; document.title = `${post.title} | Spotlight Puerto Rico`; let meta = document.querySelector('meta[name="description"]') as HTMLMetaElement | null; if (!meta) { meta = document.createElement("meta"); meta.name = "description"; document.head.appendChild(meta); } meta.content = post.description; const schema = document.createElement("script"); schema.type = "application/ld+json"; schema.id = "spotlight-article-schema"; schema.text = JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: post.title, description: post.description, datePublished: "2026-07-12", author: { "@type": "Organization", name: "Spotlight Puerto Rico" }, publisher: { "@type": "Organization", name: "Spotlight Puerto Rico", url: "https://spotlightpuertorico.com" }, mainEntityOfPage: `https://spotlightpuertorico.com/blog/${post.slug}` }); document.head.appendChild(schema); return () => { schema.remove(); document.title = "Spotlight Puerto Rico"; }; }, [post]);
  if (!post) return <div className="min-h-[60vh] grid place-items-center"><div className="text-center"><h1 className="font-display text-2xl font-bold">Guide not found</h1><Link href="/blog">Return to travel guides</Link></div></div>;
  return <article className="min-h-screen bg-white pb-20"><div className="relative h-72 md:h-[430px]"><img src={post.image} alt="" className="w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/35 to-black/10" /><div className="absolute inset-x-0 bottom-0 container mx-auto max-w-4xl px-4 pb-8 text-white"><Link href="/blog"><span className="inline-flex items-center gap-1 text-sm text-white/75"><ArrowLeft className="w-4 h-4" /> Travel guides</span></Link><h1 className="font-display text-3xl md:text-5xl font-bold text-white mt-4">{post.title}</h1><p className="text-white/70 mt-2">{post.date} · {post.read}</p></div></div><div className="container mx-auto max-w-3xl px-4 py-9"><p className="text-xl leading-relaxed text-slate-600 font-medium">{post.description}</p>{post.sections.map((section, index) => <section key={section.heading} className="mt-9"><h2 className="font-display text-2xl font-bold">{section.heading}</h2>{section.paragraphs.map((text) => <p key={text} className="text-slate-600 leading-8 mt-4">{text}</p>)}{index === 0 && <AdSlot placement="blog-after-introduction" />}</section>)}<div className="mt-10 rounded-2xl bg-primary/5 border border-primary/15 p-5"><p className="font-display font-bold flex items-center gap-2"><MapPin className="w-5 h-5 text-primary" /> Keep exploring Puerto Rico</p><div className="flex flex-wrap gap-2 mt-3"><Link href="/activities"><span className="text-sm font-bold text-primary">Browse places →</span></Link><Link href="/directory"><span className="text-sm font-bold text-primary">Find local businesses →</span></Link><Link href="/experiences"><span className="text-sm font-bold text-primary">Book experiences →</span></Link></div></div></div></article>;
}
