-- Social proof and community reviews for businesses and public places.

create or replace function public.get_saved_item_count(item_href text)
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::bigint from public.saved_items where href = item_href;
$$;

revoke all on function public.get_saved_item_count(text) from public;
grant execute on function public.get_saved_item_count(text) to anon, authenticated;

create table if not exists public.place_reviews (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  user_id text not null,
  rating smallint not null check (rating between 1 and 5),
  title text,
  body text not null check (char_length(body) between 2 and 4000),
  author_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (activity_id, user_id)
);

create index if not exists place_reviews_activity_created_idx on public.place_reviews(activity_id, created_at desc);
alter table public.place_reviews enable row level security;

drop policy if exists "Place reviews are public" on public.place_reviews;
create policy "Place reviews are public" on public.place_reviews for select using (true);

drop policy if exists "Users create their own place reviews" on public.place_reviews;
create policy "Users create their own place reviews" on public.place_reviews for insert to authenticated
with check (user_id = auth.uid()::text);

drop policy if exists "Users update their own place reviews" on public.place_reviews;
create policy "Users update their own place reviews" on public.place_reviews for update to authenticated
using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);

drop policy if exists "Users delete their own place reviews" on public.place_reviews;
create policy "Users delete their own place reviews" on public.place_reviews for delete to authenticated
using (user_id = auth.uid()::text);
